import '../Models/element_model.dart';

final List<ElementModel> elementsList = [
  // Latest discovered elements (Super heavy elements)
  ElementModel(
    atomicNumber: 118,
    symbol: 'Og',
    name: 'Oganesson',
    category: 'Noble Gas',
    atomicWeight: 294.0,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶',
    period: 7,
    group: 18,
    description: 'Oganesson is a synthetic chemical element. It was first synthesized in 2002 and is one of the most recent additions to the periodic table.',
    uses: 'Currently, no practical uses due to its extremely short half-life and high radioactivity.',
    properties: 'Superheavy, radioactive, synthetic element with very short half-life',
    discoveredBy: 'Joint team from JINR and LLNL',
    discoveredYear: 2002,
    state: 'Unknown (predicted solid)',
    color: 'Unknown', atomicMass: 2,
  ),
  ElementModel(
    atomicNumber: 117,
    symbol: 'Ts',
    name: 'Tennessine',
    category: 'Halogen',
    atomicWeight: 294.0,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵',
    period: 7,
    group: 17,
    description: 'Tennessine is a synthetic superheavy element named after Tennessee.',
    uses: 'No practical uses due to extremely short half-life.',
    properties: 'Radioactive, synthetic, superheavy halogen',
    discoveredBy: 'JINR-ORNL-Vanderbilt collaboration',
    discoveredYear: 2010,
    state: 'Unknown (predicted solid)',
    color: 'Unknown', atomicMass: 3,
  ),
  ElementModel(
    atomicNumber: 116,
    symbol: 'Lv',
    name: 'Livermorium',
    category: 'Post-Transition Metal',
    atomicWeight: 293.0,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴',
    period: 7,
    group: 16,
    description: 'Livermorium is a synthetic superheavy element named after Lawrence Livermore National Laboratory.',
    uses: 'No practical applications due to its instability.',
    properties: 'Extremely radioactive and unstable synthetic element',
    discoveredBy: 'JINR and LLNL',
    discoveredYear: 2000,
    state: 'Unknown (predicted solid)',
    color: 'Unknown', atomicMass: 4,
  ),
  ElementModel(
    atomicNumber: 115,
    symbol: 'Mc',
    name: 'Moscovium',
    category: 'Post-Transition Metal',
    atomicWeight: 288.0,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³',
    period: 7,
    group: 15,
    description: 'Moscovium is a synthetic element named after Moscow region.',
    uses: 'Research purposes only due to short half-life.',
    properties: 'Radioactive, synthetic superheavy element',
    discoveredBy: 'JINR and LLNL',
    discoveredYear: 2003,
    state: 'Unknown (predicted solid)',
    color: 'Unknown', atomicMass: 4,
  ),
  ElementModel(
    atomicNumber: 114,
    symbol: 'Fl',
    name: 'Flerovium',
    category: 'Post-Transition Metal',
    atomicWeight: 289.0,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²',
    period: 7,
    group: 14,
    description: 'Flerovium is a synthetic superheavy element named after Soviet physicist Georgy Flyorov.',
    uses: 'Scientific research only.',
    properties: 'Extremely unstable and radioactive',
    discoveredBy: 'JINR',
    discoveredYear: 1998,
    state: 'Unknown (predicted solid)',
    color: 'Unknown', atomicMass: 4,
  ),
  ElementModel(
    atomicNumber: 113,
    symbol: 'Nh',
    name: 'Nihonium',
    category: 'Post-Transition Metal',
    atomicWeight: 286.0,
    electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹',
    period: 7,
    group: 13,
    description: 'Nihonium is a synthetic element and was the first element discovered in Asia.',
    uses: 'No practical applications due to extremely short half-life.',
    properties: 'Synthetic, radioactive, superheavy element',
    discoveredBy: 'RIKEN (Japan)',
    discoveredYear: 2004,
    state: 'Unknown (predicted solid)',
    color: 'Unknown', atomicMass: 7,
  ),
  // Common elements for comparison
  ElementModel(
    atomicNumber: 1,
    symbol: 'H',
    name: 'Hydrogen',
    category: 'Nonmetal',
    atomicWeight: 1.008,
    electronConfiguration: '1s¹',
    period: 1,
    group: 1,
    description: 'Hydrogen is the lightest element and the most abundant chemical substance in the universe.',
    uses: 'Fuel for rockets, production of ammonia, hydrogenation of oils, fuel cells.',
    properties: 'Colorless, odorless, tasteless, flammable gas',
    discoveredBy: 'Henry Cavendish',
    discoveredYear: 1766,
    state: 'Gas',
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    density: 0.00008988,
    color: 'Colorless', atomicMass: 6,
  ),
  ElementModel(
    atomicNumber: 2,
    symbol: 'He',
    name: 'Helium',
    category: 'Noble Gas',
    atomicWeight: 4.003,
    electronConfiguration: '1s²',
    period: 1,
    group: 18,
    description: 'Helium is a colorless, odorless, tasteless, non-toxic, inert, monatomic gas.',
    uses: 'Balloon filling, cryogenics, breathing mixtures for deep-sea diving, protective atmosphere for welding.',
    properties: 'Inert, low density, low solubility',
    discoveredBy: 'Pierre Janssen and Norman Lockyer',
    discoveredYear: 1868,
    state: 'Gas',
    meltingPoint: -272.20,
    boilingPoint: -268.93,
    density: 0.0001785,
    color: 'Colorless', atomicMass: 66,
  ),
  ElementModel(
    atomicNumber: 6,
    symbol: 'C',
    name: 'Carbon',
    category: 'Nonmetal',
    atomicWeight: 12.011,
    electronConfiguration: '1s² 2s² 2p²',
    period: 2,
    group: 14,
    description: 'Carbon is essential to all known living systems and forms the basis of organic chemistry.',
    uses: 'Steel production, diamonds, graphite, carbon fiber, pharmaceuticals, plastics.',
    properties: 'Forms four covalent bonds, exists in multiple allotropes',
    discoveredBy: 'Known since antiquity',
    discoveredYear: null,
    state: 'Solid',
    meltingPoint: 3550,
    boilingPoint: 4027,
    density: 2.267,
    color: 'Black (graphite), Colorless (diamond)', atomicMass: 55,
  ),
  ElementModel(
    atomicNumber: 8,
    symbol: 'O',
    name: 'Oxygen',
    category: 'Nonmetal',
    atomicWeight: 15.999,
    electronConfiguration: '1s² 2s² 2p⁴',
    period: 2,
    group: 16,
    description: 'Oxygen is essential for cellular respiration and combustion processes.',
    uses: 'Breathing apparatus, steel production, water purification, rocket fuel oxidizer.',
    properties: 'Highly reactive, supports combustion, paramagnetic',
    discoveredBy: 'Carl Wilhelm Scheele and Joseph Priestley',
    discoveredYear: 1774,
    state: 'Gas',
    meltingPoint: -218.79,
    boilingPoint: -182.95,
    density: 0.001429,
    color: 'Colorless', atomicMass: 43,
  ),
  ElementModel(
    atomicNumber: 79,
    symbol: 'Au',
    name: 'Gold',
    category: 'Transition Metal',
    atomicWeight: 196.967,
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    period: 6,
    group: 11,
    description: 'Gold is a precious metal known for its beauty, durability, and resistance to corrosion.',
    uses: 'Jewelry, electronics, dentistry, monetary systems, aerospace applications.',
    properties: 'Highly conductive, malleable, ductile, corrosion-resistant',
    discoveredBy: 'Known since antiquity',
    discoveredYear: null,
    state: 'Solid',
    meltingPoint: 1064.18,
    boilingPoint: 2856,
    density: 19.282,
    color: 'Golden yellow', atomicMass: 54,
  ),
  ElementModel(
    atomicNumber: 26,
    symbol: 'Fe',
    name: 'Iron',
    category: 'Transition Metal',
    atomicWeight: 55.845,
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    period: 4,
    group: 8,
    description: 'Iron is the most common element on Earth by mass and essential for life.',
    uses: 'Steel production, construction, transportation, hemoglobin in blood.',
    properties: 'Magnetic, forms multiple oxidation states, essential for life',
    discoveredBy: 'Known since antiquity',
    discoveredYear: null,
    state: 'Solid',
    meltingPoint: 1538,
    boilingPoint: 2861,
    density: 7.874,
    color: 'Metallic gray', atomicMass: 45,
  ),
  ElementModel(
    atomicNumber: 47,
    symbol: 'Ag',
    name: 'Silver',
    category: 'Transition Metal',
    atomicWeight: 107.868,
    electronConfiguration: '[Kr] 4d¹⁰ 5s¹',
    period: 5,
    group: 11,
    description: 'Silver is a lustrous white precious metal with the highest electrical conductivity.',
    uses: 'Jewelry, electronics, photography, antimicrobial applications, mirrors.',
    properties: 'Highest electrical and thermal conductivity, antimicrobial',
    discoveredBy: 'Known since antiquity',
    discoveredYear: null,
    state: 'Solid',
    meltingPoint: 961.78,
    boilingPoint: 2162,
    density: 10.501,
    color: 'Silvery white', atomicMass: 67,
  ),
  ElementModel(
    atomicNumber: 29,
    symbol: 'Cu',
    name: 'Copper',
    category: 'Transition Metal',
    atomicWeight: 63.546,
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    period: 4,
    group: 11,
    description: 'Copper is a soft, malleable metal with excellent electrical conductivity.',
    uses: 'Electrical wiring, plumbing, coins, antimicrobial surfaces, alloys.',
    properties: 'Excellent conductor, antimicrobial, forms green patina',
    discoveredBy: 'Known since antiquity',
    discoveredYear: null,
    state: 'Solid',
    meltingPoint: 1084.62,
    boilingPoint: 2562,
    density: 8.96,
    color: 'Reddish orange', atomicMass: 32,
  ),
  ElementModel(
    atomicNumber: 92,
    symbol: 'U',
    name: 'Uranium',
    category: 'Actinide',
    atomicWeight: 238.029,
    electronConfiguration: '[Rn] 5f³ 6d¹ 7s²',
    period: 7,
    group: 3,
    description: 'Uranium is a radioactive metallic element used as fuel in nuclear reactors.',
    uses: 'Nuclear fuel, nuclear weapons, medical isotopes, dating geological samples.',
    properties: 'Radioactive, heavy metal, fissile',
    discoveredBy: 'Martin Heinrich Klaproth',
    discoveredYear: 1789,
    state: 'Solid',
    meltingPoint: 1135,
    boilingPoint: 4131,
    density: 19.1,
    color: 'Silvery gray', atomicMass: 678,
  ),
  ElementModel(
    atomicNumber: 94,
    symbol: 'Pu',
    name: 'Plutonium',
    category: 'Actinide',
    atomicWeight: 244.0,
    electronConfiguration: '[Rn] 5f⁶ 7s²',
    period: 7,
    group: 3,
    description: 'Plutonium is a radioactive metallic element used in nuclear weapons and reactors.',
    uses: 'Nuclear weapons, nuclear fuel, radioisotope thermoelectric generators.',
    properties: 'Highly radioactive, toxic, fissile material',
    discoveredBy: 'Glenn T. Seaborg and team',
    discoveredYear: 1940,
    state: 'Solid',
    meltingPoint: 640,
    boilingPoint: 3228,
    density: 19.86,
    color: 'Silvery gray', atomicMass: 54,
  ),
];
