import '../Models/formula_model.dart';

final List<FormulaModel> formulaList = [
  FormulaModel(
    symbol: 'H₂O',
    name: 'Water',
    molWeight: '18.02 g/mol',
    description: 'Colorless, odorless, tasteless liquid essential for life.',
    uses: 'Used in drinking, cleaning, and industrial processes.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'NaCl',
    name: 'Sodium Chloride',
    molWeight: '58.44 g/mol',
    description: 'Ionic compound of sodium and chloride ions.',
    uses: 'Used as table salt and food preservative.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'CO₂',
    name: 'Carbon Dioxide',
    molWeight: '44.01 g/mol',
    description: 'Colorless gas produced during respiration and combustion.',
    uses: 'Used in fire extinguishers, carbonated drinks, and photosynthesis.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'CH₄',
    name: 'Methane',
    molWeight: '16.04 g/mol',
    description: 'Simplest alkane and main component of natural gas.',
    uses: 'Used as fuel for heating and in chemical synthesis.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'C₆H₁₂O₆',
    name: 'Glucose',
    molWeight: '180.16 g/mol',
    description: 'Simple sugar and primary energy source in cellular respiration.',
    uses: 'Used in cellular respiration, food industry, and IV solutions.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'O₂',
    name: 'Oxygen',
    molWeight: '32.00 g/mol',
    description: 'Diatomic gas essential for aerobic respiration.',
    uses: 'Used in hospitals, welding, space life support, and combustion.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'NH₃',
    name: 'Ammonia',
    molWeight: '17.03 g/mol',
    description: 'Pungent-smelling gas composed of nitrogen and hydrogen.',
    uses: 'Used in fertilizers, cleaning agents, and refrigeration.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'HCl',
    name: 'Hydrochloric Acid',
    molWeight: '36.46 g/mol',
    description: 'Strong acid naturally found in gastric acid.',
    uses: 'Used in metal cleaning, food processing, and laboratory analysis.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'C₂H₅OH',
    name: 'Ethanol',
    molWeight: '46.07 g/mol',
    description: 'Alcohol commonly used as solvent and fuel additive.',
    uses: 'Used in sanitizers, fuel, beverages, and as solvent.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'CaCO₃',
    name: 'Calcium Carbonate',
    molWeight: '100.09 g/mol',
    description: 'White crystalline compound found in limestone and marble.',
    uses: 'Used in construction, antacids, chalk, and paper production.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'H₂SO₄',
    name: 'Sulfuric Acid',
    molWeight: '98.08 g/mol',
    description: 'Strong mineral acid, highly corrosive.',
    uses: 'Used in battery acid, fertilizer production, and metal processing.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'NaOH',
    name: 'Sodium Hydroxide',
    molWeight: '40.00 g/mol',
    description: 'Strong base, highly caustic white solid.',
    uses: 'Used in soap making, drain cleaning, and paper production.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'C₈H₁₈',
    name: 'Octane',
    molWeight: '114.23 g/mol',
    description: 'Hydrocarbon component of gasoline.',
    uses: 'Used as fuel in internal combustion engines.',
    bond: 'Covalent',
  ),
  FormulaModel(
    symbol: 'Fe₂O₃',
    name: 'Iron(III) Oxide',
    molWeight: '159.69 g/mol',
    description: 'Reddish-brown compound commonly known as rust.',
    uses: 'Used in pigments, polishing compounds, and magnetic storage.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'KCl',
    name: 'Potassium Chloride',
    molWeight: '74.55 g/mol',
    description: 'Salt substitute and essential electrolyte.',
    uses: 'Used in fertilizers, medical treatments, and food processing.',
    bond: 'Ionic',
  ),
];