import 'package:chem_earth_app/utils/import_export.dart';

class PeriodicElementsData {
  static List<ElementModel> get allElements => [
    // Period 1
    ElementModel(atomicNumber: 1, symbol: 'H', name: 'Hydrogen', atomicMass: 1.008, category: 'Nonmetal', group: 1, period: 1, electronegativity: 2.20, meltingPoint: -259.16, boilingPoint: -252.87, density: 0.08988, electronConfiguration: '1s¹', description: 'Hydrogen is the lightest and most abundant element in the universe. It is colorless, odorless, and highly flammable.'),
    ElementModel(atomicNumber: 2, symbol: 'He', name: 'Helium', atomicMass: 4.003, category: 'Noble Gas', group: 18, period: 1, electronegativity: null, meltingPoint: -272.20, boilingPoint: -268.93, density: 0.1786, electronConfiguration: '1s²', description: 'Helium is a noble gas that is colorless, odorless, and inert under standard conditions.'),

    // Period 2
    ElementModel(atomicNumber: 3, symbol: 'Li', name: 'Lithium', atomicMass: 6.94, category: 'Alkali Metal', group: 1, period: 2, electronegativity: 0.98, meltingPoint: 180.50, boilingPoint: 1342, density: 0.534, electronConfiguration: '[He] 2s¹', description: 'Lithium is the lightest metal and is highly reactive. It is used in batteries and psychiatric medications.'),
    ElementModel(atomicNumber: 4, symbol: 'Be', name: 'Beryllium', atomicMass: 9.012, category: 'Alkaline Earth Metal', group: 2, period: 2, electronegativity: 1.57, meltingPoint: 1287, boilingPoint: 2471, density: 1.85, electronConfiguration: '[He] 2s²', description: 'Beryllium is a lightweight but strong metal used in aerospace applications and X-ray equipment.'),
    ElementModel(atomicNumber: 5, symbol: 'B', name: 'Boron', atomicMass: 10.81, category: 'Metalloid', group: 13, period: 2, electronegativity: 2.04, meltingPoint: 2076, boilingPoint: 4000, density: 2.34, electronConfiguration: '[He] 2s² 2p¹', description: 'Boron is a metalloid essential for plant growth and used in glass and ceramics.'),
    ElementModel(atomicNumber: 6, symbol: 'C', name: 'Carbon', atomicMass: 12.011, category: 'Nonmetal', group: 14, period: 2, electronegativity: 2.55, meltingPoint: 3550, boilingPoint: 4027, density: 2.267, electronConfiguration: '[He] 2s² 2p²', description: 'Carbon is the basis of all organic compounds and life on Earth. It forms millions of compounds.'),
    ElementModel(atomicNumber: 7, symbol: 'N', name: 'Nitrogen', atomicMass: 14.007, category: 'Nonmetal', group: 15, period: 2, electronegativity: 3.04, meltingPoint: -210.00, boilingPoint: -195.79, density: 0.0012506, electronConfiguration: '[He] 2s² 2p³', description: 'Nitrogen makes up about 78% of Earth\'s atmosphere and is essential for proteins and DNA.'),
    ElementModel(atomicNumber: 8, symbol: 'O', name: 'Oxygen', atomicMass: 15.999, category: 'Nonmetal', group: 16, period: 2, electronegativity: 3.44, meltingPoint: -218.79, boilingPoint: -182.95, density: 0.001429, electronConfiguration: '[He] 2s² 2p⁴', description: 'Oxygen is essential for combustion and respiration. It makes up about 21% of Earth\'s atmosphere.'),
    ElementModel(atomicNumber: 9, symbol: 'F', name: 'Fluorine', atomicMass: 18.998, category: 'Halogen', group: 17, period: 2, electronegativity: 3.98, meltingPoint: -219.67, boilingPoint: -188.11, density: 0.001696, electronConfiguration: '[He] 2s² 2p⁵', description: 'Fluorine is the most reactive and electronegative element. It is used in toothpaste and Teflon.'),
    ElementModel(atomicNumber: 10, symbol: 'Ne', name: 'Neon', atomicMass: 20.180, category: 'Noble Gas', group: 18, period: 2, electronegativity: null, meltingPoint: -248.59, boilingPoint: -246.05, density: 0.0008999, electronConfiguration: '[He] 2s² 2p⁶', description: 'Neon is a noble gas that glows orange-red in electric discharge. It is used in neon signs.'),

    // Period 3
    ElementModel(atomicNumber: 11, symbol: 'Na', name: 'Sodium', atomicMass: 22.990, category: 'Alkali Metal', group: 1, period: 3, electronegativity: 0.93, meltingPoint: 97.72, boilingPoint: 883, density: 0.968, electronConfiguration: '[Ne] 3s¹', description: 'Sodium is a soft, reactive metal essential for nerve function and found in table salt.'),
    ElementModel(atomicNumber: 12, symbol: 'Mg', name: 'Magnesium', atomicMass: 24.305, category: 'Alkaline Earth Metal', group: 2, period: 3, electronegativity: 1.31, meltingPoint: 650, boilingPoint: 1090, density: 1.738, electronConfiguration: '[Ne] 3s²', description: 'Magnesium is a light metal used in alloys and is essential for chlorophyll in plants.'),
    ElementModel(atomicNumber: 13, symbol: 'Al', name: 'Aluminum', atomicMass: 26.982, category: 'Post-Transition Metal', group: 13, period: 3, electronegativity: 1.61, meltingPoint: 660.32, boilingPoint: 2519, density: 2.70, electronConfiguration: '[Ne] 3s² 3p¹', description: 'Aluminum is a lightweight, corrosion-resistant metal widely used in construction and transportation.'),
    ElementModel(atomicNumber: 14, symbol: 'Si', name: 'Silicon', atomicMass: 28.085, category: 'Metalloid', group: 14, period: 3, electronegativity: 1.90, meltingPoint: 1414, boilingPoint: 3265, density: 2.3296, electronConfiguration: '[Ne] 3s² 3p²', description: 'Silicon is the basis of semiconductors and computer chips, and is abundant in sand and rocks.'),
    ElementModel(atomicNumber: 15, symbol: 'P', name: 'Phosphorus', atomicMass: 30.974, category: 'Nonmetal', group: 15, period: 3, electronegativity: 2.19, meltingPoint: 44.15, boilingPoint: 280.5, density: 1.823, electronConfiguration: '[Ne] 3s² 3p³', description: 'Phosphorus is essential for DNA, RNA, and ATP. It is used in fertilizers and matches.'),
    ElementModel(atomicNumber: 16, symbol: 'S', name: 'Sulfur', atomicMass: 32.06, category: 'Nonmetal', group: 16, period: 3, electronegativity: 2.58, meltingPoint: 115.21, boilingPoint: 444.61, density: 1.96, electronConfiguration: '[Ne] 3s² 3p⁴', description: 'Sulfur is found in proteins and vitamins. It is used in gunpowder and vulcanizing rubber.'),
    ElementModel(atomicNumber: 17, symbol: 'Cl', name: 'Chlorine', atomicMass: 35.45, category: 'Halogen', group: 17, period: 3, electronegativity: 3.16, meltingPoint: -101.5, boilingPoint: -34.04, density: 0.003214, electronConfiguration: '[Ne] 3s² 3p⁵', description: 'Chlorine is a reactive gas used for water purification and in the production of PVC.'),
    ElementModel(atomicNumber: 18, symbol: 'Ar', name: 'Argon', atomicMass: 39.948, category: 'Noble Gas', group: 18, period: 3, electronegativity: null, meltingPoint: -189.35, boilingPoint: -185.85, density: 0.0017837, electronConfiguration: '[Ne] 3s² 3p⁶', description: 'Argon is an inert gas used in welding and light bulbs to prevent oxidation.'),

    // Period 4
    ElementModel(atomicNumber: 19, symbol: 'K', name: 'Potassium', atomicMass: 39.098, category: 'Alkali Metal', group: 1, period: 4, electronegativity: 0.82, meltingPoint: 63.5, boilingPoint: 759, density: 0.89, electronConfiguration: '[Ar] 4s¹', description: 'Potassium is essential for nerve and muscle function and is found in bananas and other foods.'),
    ElementModel(atomicNumber: 20, symbol: 'Ca', name: 'Calcium', atomicMass: 40.078, category: 'Alkaline Earth Metal', group: 2, period: 4, electronegativity: 1.00, meltingPoint: 842, boilingPoint: 1484, density: 1.54, electronConfiguration: '[Ar] 4s²', description: 'Calcium is essential for bones and teeth. It is the most abundant metal in the human body.'),
    ElementModel(atomicNumber: 21, symbol: 'Sc', name: 'Scandium', atomicMass: 44.956, category: 'Transition Metal', group: 3, period: 4, electronegativity: 1.36, meltingPoint: 1541, boilingPoint: 2836, density: 2.985, electronConfiguration: '[Ar] 3d¹ 4s²', description: 'Scandium is a rare metal used in aerospace alloys and high-intensity lighting.'),
    ElementModel(atomicNumber: 22, symbol: 'Ti', name: 'Titanium', atomicMass: 47.867, category: 'Transition Metal', group: 4, period: 4, electronegativity: 1.54, meltingPoint: 1668, boilingPoint: 3287, density: 4.506, electronConfiguration: '[Ar] 3d² 4s²', description: 'Titanium is a strong, lightweight, corrosion-resistant metal used in aerospace and medical implants.'),
    ElementModel(atomicNumber: 23, symbol: 'V', name: 'Vanadium', atomicMass: 50.942, category: 'Transition Metal', group: 5, period: 4, electronegativity: 1.63, meltingPoint: 1910, boilingPoint: 3407, density: 6.0, electronConfiguration: '[Ar] 3d³ 4s²', description: 'Vanadium is used to strengthen steel and in catalysts for chemical processes.'),
    ElementModel(atomicNumber: 24, symbol: 'Cr', name: 'Chromium', atomicMass: 51.996, category: 'Transition Metal', group: 6, period: 4, electronegativity: 1.66, meltingPoint: 1907, boilingPoint: 2671, density: 7.15, electronConfiguration: '[Ar] 3d⁵ 4s¹', description: 'Chromium is used in stainless steel and chrome plating for its corrosion resistance and shine.'),
    ElementModel(atomicNumber: 25, symbol: 'Mn', name: 'Manganese', atomicMass: 54.938, category: 'Transition Metal', group: 7, period: 4, electronegativity: 1.55, meltingPoint: 1246, boilingPoint: 2061, density: 7.21, electronConfiguration: '[Ar] 3d⁵ 4s²', description: 'Manganese is essential for steel production and is involved in photosynthesis in plants.'),
    ElementModel(atomicNumber: 26, symbol: 'Fe', name: 'Iron', atomicMass: 55.845, category: 'Transition Metal', group: 8, period: 4, electronegativity: 1.83, meltingPoint: 1538, boilingPoint: 2861, density: 7.874, electronConfiguration: '[Ar] 3d⁶ 4s²', description: 'Iron is essential for oxygen transport in blood and is the most widely used metal.'),
    ElementModel(atomicNumber: 27, symbol: 'Co', name: 'Cobalt', atomicMass: 58.933, category: 'Transition Metal', group: 9, period: 4, electronegativity: 1.88, meltingPoint: 1495, boilingPoint: 2927, density: 8.86, electronConfiguration: '[Ar] 3d⁷ 4s²', description: 'Cobalt is used in rechargeable batteries and is essential for vitamin B12.'),
    ElementModel(atomicNumber: 28, symbol: 'Ni', name: 'Nickel', atomicMass: 58.693, category: 'Transition Metal', group: 10, period: 4, electronegativity: 1.91, meltingPoint: 1455, boilingPoint: 2913, density: 8.912, electronConfiguration: '[Ar] 3d⁸ 4s²', description: 'Nickel is used in stainless steel, coins, and rechargeable batteries.'),
    ElementModel(atomicNumber: 29, symbol: 'Cu', name: 'Copper', atomicMass: 63.546, category: 'Transition Metal', group: 11, period: 4, electronegativity: 1.90, meltingPoint: 1084.62, boilingPoint: 2562, density: 8.96, electronConfiguration: '[Ar] 3d¹⁰ 4s¹', description: 'Copper is an excellent conductor of electricity and heat, used in wiring and plumbing.'),
    ElementModel(atomicNumber: 30, symbol: 'Zn', name: 'Zinc', atomicMass: 65.38, category: 'Transition Metal', group: 12, period: 4, electronegativity: 1.65, meltingPoint: 419.53, boilingPoint: 907, density: 7.134, electronConfiguration: '[Ar] 3d¹⁰ 4s²', description: 'Zinc is essential for immune function and is used in galvanizing steel to prevent rust.'),
    ElementModel(atomicNumber: 31, symbol: 'Ga', name: 'Gallium', atomicMass: 69.723, category: 'Post-Transition Metal', group: 13, period: 4, electronegativity: 1.81, meltingPoint: 29.76, boilingPoint: 2204, density: 5.91, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹', description: 'Gallium melts in your hand and is used in semiconductors and LED lights.'),
    ElementModel(atomicNumber: 32, symbol: 'Ge', name: 'Germanium', atomicMass: 72.630, category: 'Metalloid', group: 14, period: 4, electronegativity: 2.01, meltingPoint: 938.25, boilingPoint: 2833, density: 5.323, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²', description: 'Germanium is a semiconductor used in transistors and fiber optic systems.'),
    ElementModel(atomicNumber: 33, symbol: 'As', name: 'Arsenic', atomicMass: 74.922, category: 'Metalloid', group: 15, period: 4, electronegativity: 2.18, meltingPoint: 817, boilingPoint: 614, density: 5.727, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³', description: 'Arsenic is toxic but used in some semiconductors and wood preservatives.'),
    ElementModel(atomicNumber: 34, symbol: 'Se', name: 'Selenium', atomicMass: 78.971, category: 'Nonmetal', group: 16, period: 4, electronegativity: 2.55, meltingPoint: 221, boilingPoint: 685, density: 4.809, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴', description: 'Selenium is essential for antioxidant enzymes and is used in photocells.'),
    ElementModel(atomicNumber: 35, symbol: 'Br', name: 'Bromine', atomicMass: 79.904, category: 'Halogen', group: 17, period: 4, electronegativity: 2.96, meltingPoint: -7.2, boilingPoint: 58.8, density: 3.1028, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵', description: 'Bromine is a toxic, reddish-brown liquid used in flame retardants and pharmaceuticals.'),
    ElementModel(atomicNumber: 36, symbol: 'Kr', name: 'Krypton', atomicMass: 83.798, category: 'Noble Gas', group: 18, period: 4, electronegativity: 3.00, meltingPoint: -157.36, boilingPoint: -153.22, density: 0.003733, electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶', description: 'Krypton is used in high-performance light bulbs and lasers.'),

    // Period 5 - Adding key elements
    ElementModel(atomicNumber: 37, symbol: 'Rb', name: 'Rubidium', atomicMass: 85.468, category: 'Alkali Metal', group: 1, period: 5, electronegativity: 0.82, meltingPoint: 39.31, boilingPoint: 688, density: 1.532, electronConfiguration: '[Kr] 5s¹', description: 'Rubidium is a soft, reactive metal used in atomic clocks and research.'),
    ElementModel(atomicNumber: 38, symbol: 'Sr', name: 'Strontium', atomicMass: 87.62, category: 'Alkaline Earth Metal', group: 2, period: 5, electronegativity: 0.95, meltingPoint: 777, boilingPoint: 1382, density: 2.64, electronConfiguration: '[Kr] 5s²', description: 'Strontium is used in fireworks for red color and in some medical applications.'),
    ElementModel(atomicNumber: 39, symbol: 'Y', name: 'Yttrium', atomicMass: 88.906, category: 'Transition Metal', group: 3, period: 5, electronegativity: 1.22, meltingPoint: 1526, boilingPoint: 3345, density: 4.472, electronConfiguration: '[Kr] 4d¹ 5s²', description: 'Yttrium is used in lasers, superconductors, and cancer treatment.'),
    ElementModel(atomicNumber: 40, symbol: 'Zr', name: 'Zirconium', atomicMass: 91.224, category: 'Transition Metal', group: 4, period: 5, electronegativity: 1.33, meltingPoint: 1855, boilingPoint: 4409, density: 6.52, electronConfiguration: '[Kr] 4d² 5s²', description: 'Zirconium is extremely corrosion-resistant and used in nuclear reactors.'),

    // Continue with more elements to reach 118...
    // Adding silver and other important elements
    ElementModel(atomicNumber: 47, symbol: 'Ag', name: 'Silver', atomicMass: 107.868, category: 'Transition Metal', group: 11, period: 5, electronegativity: 1.93, meltingPoint: 961.78, boilingPoint: 2162, density: 10.501, electronConfiguration: '[Kr] 4d¹⁰ 5s¹', description: 'Silver is a precious metal with the highest electrical conductivity of any element.'),
    ElementModel(atomicNumber: 50, symbol: 'Sn', name: 'Tin', atomicMass: 118.710, category: 'Post-Transition Metal', group: 14, period: 5, electronegativity: 1.96, meltingPoint: 231.93, boilingPoint: 2602, density: 7.287, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p²', description: 'Tin is used in solder, bronze, and to coat steel cans to prevent corrosion.'),
    ElementModel(atomicNumber: 53, symbol: 'I', name: 'Iodine', atomicMass: 126.904, category: 'Halogen', group: 17, period: 5, electronegativity: 2.66, meltingPoint: 113.7, boilingPoint: 184.3, density: 4.933, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁵', description: 'Iodine is essential for thyroid function and is used as an antiseptic.'),
    ElementModel(atomicNumber: 54, symbol: 'Xe', name: 'Xenon', atomicMass: 131.293, category: 'Noble Gas', group: 18, period: 5, electronegativity: 2.60, meltingPoint: -111.75, boilingPoint: -108.09, density: 0.005887, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁶', description: 'Xenon is used in specialized lighting and anesthesia.'),

    // Period 6 - Adding key elements including Lanthanides
    ElementModel(atomicNumber: 55, symbol: 'Cs', name: 'Cesium', atomicMass: 132.905, category: 'Alkali Metal', group: 1, period: 6, electronegativity: 0.79, meltingPoint: 28.44, boilingPoint: 671, density: 1.93, electronConfiguration: '[Xe] 6s¹', description: 'Cesium is used in atomic clocks and has the lowest melting point of any metal.'),
    ElementModel(atomicNumber: 56, symbol: 'Ba', name: 'Barium', atomicMass: 137.327, category: 'Alkaline Earth Metal', group: 2, period: 6, electronegativity: 0.89, meltingPoint: 727, boilingPoint: 1845, density: 3.62, electronConfiguration: '[Xe] 6s²', description: 'Barium compounds are used in X-ray imaging and fireworks for green color.'),
    ElementModel(atomicNumber: 79, symbol: 'Au', name: 'Gold', atomicMass: 196.967, category: 'Transition Metal', group: 11, period: 6, electronegativity: 2.54, meltingPoint: 1064.18, boilingPoint: 2836, density: 19.282, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹', description: 'Gold is a precious metal prized for its beauty, corrosion resistance, and conductivity.'),
    ElementModel(atomicNumber: 80, symbol: 'Hg', name: 'Mercury', atomicMass: 200.592, category: 'Transition Metal', group: 12, period: 6, electronegativity: 2.00, meltingPoint: -38.83, boilingPoint: 356.73, density: 13.5336, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s²', description: 'Mercury is the only liquid metal at room temperature and is highly toxic.'),
    ElementModel(atomicNumber: 82, symbol: 'Pb', name: 'Lead', atomicMass: 207.2, category: 'Post-Transition Metal', group: 14, period: 6, electronegativity: 2.33, meltingPoint: 327.46, boilingPoint: 1749, density: 11.342, electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²', description: 'Lead is a dense, toxic metal once used in paint and gasoline but now heavily regulated.'),

    // Period 7 - Adding Actinides and super-heavy elements
    ElementModel(atomicNumber: 87, symbol: 'Fr', name: 'Francium', atomicMass: 223, category: 'Alkali Metal', group: 1, period: 7, electronegativity: 0.7, meltingPoint: 27, boilingPoint: 677, density: 1.87, electronConfiguration: '[Rn] 7s¹', description: 'Francium is the most reactive metal and is extremely radioactive and rare.'),
    ElementModel(atomicNumber: 88, symbol: 'Ra', name: 'Radium', atomicMass: 226, category: 'Alkaline Earth Metal', group: 2, period: 7, electronegativity: 0.9, meltingPoint: 696, boilingPoint: 1737, density: 5.5, electronConfiguration: '[Rn] 7s²', description: 'Radium is highly radioactive and was once used in luminous paints.'),
    ElementModel(atomicNumber: 92, symbol: 'U', name: 'Uranium', atomicMass: 238.029, category: 'Actinide', group: null, period: 7, electronegativity: 1.38, meltingPoint: 1135, boilingPoint: 4131, density: 18.95, electronConfiguration: '[Rn] 5f³ 6d¹ 7s²', description: 'Uranium is used as fuel in nuclear reactors and weapons.'),
    
    // Super-heavy elements (synthetic)
    ElementModel(atomicNumber: 104, symbol: 'Rf', name: 'Rutherfordium', atomicMass: 267, category: 'Transition Metal', group: 4, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d² 7s²', description: 'Rutherfordium is a synthetic, radioactive element with no known uses.'),
    ElementModel(atomicNumber: 105, symbol: 'Db', name: 'Dubnium', atomicMass: 268, category: 'Transition Metal', group: 5, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d³ 7s²', description: 'Dubnium is a synthetic, radioactive element created in particle accelerators.'),
    ElementModel(atomicNumber: 106, symbol: 'Sg', name: 'Seaborgium', atomicMass: 271, category: 'Transition Metal', group: 6, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d⁴ 7s²', description: 'Seaborgium is a synthetic element named after Glenn T. Seaborg.'),
    ElementModel(atomicNumber: 107, symbol: 'Bh', name: 'Bohrium', atomicMass: 272, category: 'Transition Metal', group: 7, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d⁵ 7s²', description: 'Bohrium is a synthetic element named after Niels Bohr.'),
    ElementModel(atomicNumber: 108, symbol: 'Hs', name: 'Hassium', atomicMass: 277, category: 'Transition Metal', group: 8, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d⁶ 7s²', description: 'Hassium is a synthetic element named after the German state of Hesse.'),
    ElementModel(atomicNumber: 109, symbol: 'Mt', name: 'Meitnerium', atomicMass: 276, category: 'Transition Metal', group: 9, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d⁷ 7s²', description: 'Meitnerium is named after Lise Meitner, a pioneer in nuclear physics.'),
    ElementModel(atomicNumber: 110, symbol: 'Ds', name: 'Darmstadtium', atomicMass: 281, category: 'Transition Metal', group: 10, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d⁸ 7s²', description: 'Darmstadtium is named after Darmstadt, Germany, where it was discovered.'),
    ElementModel(atomicNumber: 111, symbol: 'Rg', name: 'Roentgenium', atomicMass: 280, category: 'Transition Metal', group: 11, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d⁹ 7s²', description: 'Roentgenium is named after Wilhelm Röntgen, discoverer of X-rays.'),
    ElementModel(atomicNumber: 112, symbol: 'Cn', name: 'Copernicium', atomicMass: 285, category: 'Transition Metal', group: 12, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s²', description: 'Copernicium is named after astronomer Nicolaus Copernicus.'),
    ElementModel(atomicNumber: 113, symbol: 'Nh', name: 'Nihonium', atomicMass: 284, category: 'Post-Transition Metal', group: 13, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹', description: 'Nihonium is named after Japan (Nihon), where it was discovered.'),
    ElementModel(atomicNumber: 114, symbol: 'Fl', name: 'Flerovium', atomicMass: 289, category: 'Post-Transition Metal', group: 14, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²', description: 'Flerovium is named after Soviet physicist Georgy Flyorov.'),
    ElementModel(atomicNumber: 115, symbol: 'Mc', name: 'Moscovium', atomicMass: 288, category: 'Post-Transition Metal', group: 15, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³', description: 'Moscovium is named after Moscow, Russia.'),
    ElementModel(atomicNumber: 116, symbol: 'Lv', name: 'Livermorium', atomicMass: 293, category: 'Post-Transition Metal', group: 16, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴', description: 'Livermorium is named after Lawrence Livermore National Laboratory.'),
    ElementModel(atomicNumber: 117, symbol: 'Ts', name: 'Tennessine', atomicMass: 294, category: 'Halogen', group: 17, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵', description: 'Tennessine is named after Tennessee, USA.'),
    ElementModel(atomicNumber: 118, symbol: 'Og', name: 'Oganesson', atomicMass: 294, category: 'Noble Gas', group: 18, period: 7, electronegativity: null, meltingPoint: null, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶', description: 'Oganesson is named after Yuri Oganessian, a pioneer in super-heavy element research.'),

    // Adding some missing essential elements from periods 4-6
    ElementModel(atomicNumber: 41, symbol: 'Nb', name: 'Niobium', atomicMass: 92.906, category: 'Transition Metal', group: 5, period: 5, electronegativity: 1.6, meltingPoint: 2477, boilingPoint: 4744, density: 8.57, electronConfiguration: '[Kr] 4d⁴ 5s¹', description: 'Niobium is used in superconducting magnets and steel alloys.'),
    ElementModel(atomicNumber: 42, symbol: 'Mo', name: 'Molybdenum', atomicMass: 95.95, category: 'Transition Metal', group: 6, period: 5, electronegativity: 2.16, meltingPoint: 2623, boilingPoint: 4639, density: 10.28, electronConfiguration: '[Kr] 4d⁵ 5s¹', description: 'Molybdenum is used in steel alloys and as a catalyst in petroleum refining.'),
    ElementModel(atomicNumber: 43, symbol: 'Tc', name: 'Technetium', atomicMass: 98, category: 'Transition Metal', group: 7, period: 5, electronegativity: 1.9, meltingPoint: 2157, boilingPoint: 4265, density: 11, electronConfiguration: '[Kr] 4d⁵ 5s²', description: 'Technetium is radioactive and used in medical imaging.'),
    ElementModel(atomicNumber: 44, symbol: 'Ru', name: 'Ruthenium', atomicMass: 101.07, category: 'Transition Metal', group: 8, period: 5, electronegativity: 2.2, meltingPoint: 2334, boilingPoint: 4150, density: 12.1, electronConfiguration: '[Kr] 4d⁷ 5s¹', description: 'Ruthenium is used in electronics and as a catalyst.'),
    ElementModel(atomicNumber: 45, symbol: 'Rh', name: 'Rhodium', atomicMass: 102.906, category: 'Transition Metal', group: 9, period: 5, electronegativity: 2.28, meltingPoint: 1964, boilingPoint: 3695, density: 12.4, electronConfiguration: '[Kr] 4d⁸ 5s¹', description: 'Rhodium is used in catalytic converters and jewelry.'),
    ElementModel(atomicNumber: 46, symbol: 'Pd', name: 'Palladium', atomicMass: 106.42, category: 'Transition Metal', group: 10, period: 5, electronegativity: 2.20, meltingPoint: 1554.8, boilingPoint: 2963, density: 12.023, electronConfiguration: '[Kr] 4d¹⁰', description: 'Palladium is used in catalytic converters and jewelry.'),
    ElementModel(atomicNumber: 48, symbol: 'Cd', name: 'Cadmium', atomicMass: 112.411, category: 'Transition Metal', group: 12, period: 5, electronegativity: 1.69, meltingPoint: 321.07, boilingPoint: 767, density: 8.69, electronConfiguration: '[Kr] 4d¹⁰ 5s²', description: 'Cadmium is toxic but used in batteries and pigments.'),
    ElementModel(atomicNumber: 49, symbol: 'In', name: 'Indium', atomicMass: 114.818, category: 'Post-Transition Metal', group: 13, period: 5, electronegativity: 1.78, meltingPoint: 156.6, boilingPoint: 2072, density: 7.31, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p¹', description: 'Indium is used in touchscreens and semiconductors.'),
    ElementModel(atomicNumber: 51, symbol: 'Sb', name: 'Antimony', atomicMass: 121.760, category: 'Metalloid', group: 15, period: 5, electronegativity: 2.05, meltingPoint: 630.63, boilingPoint: 1587, density: 6.685, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p³', description: 'Antimony is used in flame retardants and semiconductor devices.'),
    ElementModel(atomicNumber: 52, symbol: 'Te', name: 'Tellurium', atomicMass: 127.60, category: 'Metalloid', group: 16, period: 5, electronegativity: 2.1, meltingPoint: 449.51, boilingPoint: 988, density: 6.232, electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁴', description: 'Tellurium is used in solar panels and thermoelectric devices.'),

    // Complete Lanthanide series
    ElementModel(atomicNumber: 59, symbol: 'Pr', name: 'Praseodymium', atomicMass: 140.908, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.13, meltingPoint: 931, boilingPoint: 3520, density: 6.773, electronConfiguration: '[Xe] 4f³ 6s²', description: 'Praseodymium is used in permanent magnets and glass coloring.'),
    ElementModel(atomicNumber: 61, symbol: 'Pm', name: 'Promethium', atomicMass: 145, category: 'Lanthanide', group: null, period: 6, electronegativity: null, meltingPoint: 1042, boilingPoint: 3000, density: 7.26, electronConfiguration: '[Xe] 4f⁵ 6s²', description: 'Promethium is radioactive and used in nuclear batteries.'),
    ElementModel(atomicNumber: 62, symbol: 'Sm', name: 'Samarium', atomicMass: 150.36, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.17, meltingPoint: 1072, boilingPoint: 1794, density: 7.52, electronConfiguration: '[Xe] 4f⁶ 6s²', description: 'Samarium is used in powerful permanent magnets and nuclear reactors.'),
    ElementModel(atomicNumber: 63, symbol: 'Eu', name: 'Europium', atomicMass: 151.964, category: 'Lanthanide', group: null, period: 6, electronegativity: null, meltingPoint: 822, boilingPoint: 1529, density: 5.244, electronConfiguration: '[Xe] 4f⁷ 6s²', description: 'Europium is used in fluorescent lamps and television screens.'),
    ElementModel(atomicNumber: 64, symbol: 'Gd', name: 'Gadolinium', atomicMass: 157.25, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.20, meltingPoint: 1313, boilingPoint: 3273, density: 7.90, electronConfiguration: '[Xe] 4f⁷ 5d¹ 6s²', description: 'Gadolinium is used in MRI contrast agents and neutron capture.'),
    ElementModel(atomicNumber: 65, symbol: 'Tb', name: 'Terbium', atomicMass: 158.925, category: 'Lanthanide', group: null, period: 6, electronegativity: null, meltingPoint: 1356, boilingPoint: 3230, density: 8.23, electronConfiguration: '[Xe] 4f⁹ 6s²', description: 'Terbium is used in green phosphors and solid-state devices.'),
    ElementModel(atomicNumber: 66, symbol: 'Dy', name: 'Dysprosium', atomicMass: 162.500, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.22, meltingPoint: 1412, boilingPoint: 2567, density: 8.55, electronConfiguration: '[Xe] 4f¹⁰ 6s²', description: 'Dysprosium is used in high-performance magnets and nuclear reactors.'),
    ElementModel(atomicNumber: 67, symbol: 'Ho', name: 'Holmium', atomicMass: 164.930, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.23, meltingPoint: 1474, boilingPoint: 2700, density: 8.80, electronConfiguration: '[Xe] 4f¹¹ 6s²', description: 'Holmium is used in lasers and nuclear control rods.'),
    ElementModel(atomicNumber: 68, symbol: 'Er', name: 'Erbium', atomicMass: 167.259, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.24, meltingPoint: 1529, boilingPoint: 2868, density: 9.07, electronConfiguration: '[Xe] 4f¹² 6s²', description: 'Erbium is used in fiber optic communications and lasers.'),
    ElementModel(atomicNumber: 69, symbol: 'Tm', name: 'Thulium', atomicMass: 168.934, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.25, meltingPoint: 1545, boilingPoint: 1950, density: 9.32, electronConfiguration: '[Xe] 4f¹³ 6s²', description: 'Thulium is the rarest stable lanthanide and used in portable X-ray machines.'),
    ElementModel(atomicNumber: 70, symbol: 'Yb', name: 'Ytterbium', atomicMass: 173.054, category: 'Lanthanide', group: null, period: 6, electronegativity: null, meltingPoint: 824, boilingPoint: 1196, density: 6.90, electronConfiguration: '[Xe] 4f¹⁴ 6s²', description: 'Ytterbium is used in atomic clocks and laser systems.'),
    ElementModel(atomicNumber: 71, symbol: 'Lu', name: 'Lutetium', atomicMass: 174.967, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.27, meltingPoint: 1663, boilingPoint: 3402, density: 9.84, electronConfiguration: '[Xe] 4f¹⁴ 5d¹ 6s²', description: 'Lutetium is the rarest and hardest lanthanide element.'),

    // Adding Lanthanides
    ElementModel(atomicNumber: 57, symbol: 'La', name: 'Lanthanum', atomicMass: 138.905, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.10, meltingPoint: 920, boilingPoint: 3464, density: 6.145, electronConfiguration: '[Xe] 5d¹ 6s²', description: 'Lanthanum is used in camera lenses and catalysts.'),
    ElementModel(atomicNumber: 58, symbol: 'Ce', name: 'Cerium', atomicMass: 140.116, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.12, meltingPoint: 795, boilingPoint: 3443, density: 6.770, electronConfiguration: '[Xe] 4f¹ 5d¹ 6s²', description: 'Cerium is used in catalytic converters and glass polishing.'),
    ElementModel(atomicNumber: 60, symbol: 'Nd', name: 'Neodymium', atomicMass: 144.242, category: 'Lanthanide', group: null, period: 6, electronegativity: 1.14, meltingPoint: 1016, boilingPoint: 3074, density: 7.01, electronConfiguration: '[Xe] 4f⁴ 6s²', description: 'Neodymium is used in powerful permanent magnets.'),

    // Adding more transition metals
    ElementModel(atomicNumber: 72, symbol: 'Hf', name: 'Hafnium', atomicMass: 178.49, category: 'Transition Metal', group: 4, period: 6, electronegativity: 1.3, meltingPoint: 2233, boilingPoint: 4603, density: 13.31, electronConfiguration: '[Xe] 4f¹⁴ 5d² 6s²', description: 'Hafnium is used in nuclear control rods and high-temperature alloys.'),
    ElementModel(atomicNumber: 73, symbol: 'Ta', name: 'Tantalum', atomicMass: 180.948, category: 'Transition Metal', group: 5, period: 6, electronegativity: 1.5, meltingPoint: 3017, boilingPoint: 5458, density: 16.654, electronConfiguration: '[Xe] 4f¹⁴ 5d³ 6s²', description: 'Tantalum is extremely corrosion-resistant and used in electronics.'),
    ElementModel(atomicNumber: 74, symbol: 'W', name: 'Tungsten', atomicMass: 183.84, category: 'Transition Metal', group: 6, period: 6, electronegativity: 2.36, meltingPoint: 3414, boilingPoint: 5555, density: 19.25, electronConfiguration: '[Xe] 4f¹⁴ 5d⁴ 6s²', description: 'Tungsten has the highest melting point of any element and is used in light bulb filaments.'),
    ElementModel(atomicNumber: 75, symbol: 'Re', name: 'Rhenium', atomicMass: 186.207, category: 'Transition Metal', group: 7, period: 6, electronegativity: 1.9, meltingPoint: 3185, boilingPoint: 5596, density: 20.8, electronConfiguration: '[Xe] 4f¹⁴ 5d⁵ 6s²', description: 'Rhenium is one of the rarest elements and is used in jet engine components.'),
    ElementModel(atomicNumber: 76, symbol: 'Os', name: 'Osmium', atomicMass: 190.23, category: 'Transition Metal', group: 8, period: 6, electronegativity: 2.2, meltingPoint: 3033, boilingPoint: 5012, density: 22.59, electronConfiguration: '[Xe] 4f¹⁴ 5d⁶ 6s²', description: 'Osmium is the densest naturally occurring element.'),
    ElementModel(atomicNumber: 77, symbol: 'Ir', name: 'Iridium', atomicMass: 192.217, category: 'Transition Metal', group: 9, period: 6, electronegativity: 2.20, meltingPoint: 2466, boilingPoint: 4428, density: 22.56, electronConfiguration: '[Xe] 4f¹⁰ 5d⁶ 6s²', description: 'Iridium is extremely corrosion-resistant and was used to define the kilogram.'),
    ElementModel(atomicNumber: 78, symbol: 'Pt', name: 'Platinum', atomicMass: 195.084, category: 'Transition Metal', group: 10, period: 6, electronegativity: 2.28, meltingPoint: 1768.2, boilingPoint: 3825, density: 21.46, electronConfiguration: '[Xe] 4f¹⁰ 5d⁶ 6s²', description: 'Platinum is a precious metal used in catalytic converters and jewelry.'),
    ElementModel(atomicNumber: 81, symbol: 'Tl', name: 'Thallium', atomicMass: 204.38, category: 'Post-Transition Metal', group: 13, period: 6, electronegativity: 1.62, meltingPoint: 304, boilingPoint: 1473, density: 11.85, electronConfiguration: '[Xe] 4f¹⁰ 5d¹⁰ 6s² 6p¹', description: 'Thallium is highly toxic and was once used in rat poison.'),
    ElementModel(atomicNumber: 83, symbol: 'Bi', name: 'Bismuth', atomicMass: 208.980, category: 'Post-Transition Metal', group: 15, period: 6, electronegativity: 2.02, meltingPoint: 271.5, boilingPoint: 1564, density: 9.807, electronConfiguration: '[Xe] 4f¹⁰ 5d¹⁰ 6s² 6p³', description: 'Bismuth is used in cosmetics, medicines, and low-melting-point alloys.'),
    ElementModel(atomicNumber: 84, symbol: 'Po', name: 'Polonium', atomicMass: 209, category: 'Metalloid', group: 16, period: 6, electronegativity: 2.0, meltingPoint: 254, boilingPoint: 962, density: 9.32, electronConfiguration: '[Xe] 4f¹⁰ 5d¹⁰ 6s² 6p⁴', description: 'Polonium is extremely radioactive and was discovered by Marie Curie.'),
    ElementModel(atomicNumber: 85, symbol: 'At', name: 'Astatine', atomicMass: 210, category: 'Halogen', group: 17, period: 6, electronegativity: 2.2, meltingPoint: 302, boilingPoint: 337, density: 7, electronConfiguration: '[Xe] 4f¹⁰ 5d¹⁰ 6s² 6p⁵', description: 'Astatine is extremely rare and radioactive, with potential medical applications.'),
    ElementModel(atomicNumber: 86, symbol: 'Rn', name: 'Radon', atomicMass: 222, category: 'Noble Gas', group: 18, period: 6, electronegativity: 2.2, meltingPoint: -71, boilingPoint: -62, density: 0.00973, electronConfiguration: '[Xe] 4f¹⁰ 5d¹⁰ 6s² 6p⁶', description: 'Radon is a radioactive gas that can accumulate in buildings and cause lung cancer.'),

    // Adding some missing Actinides
    ElementModel(atomicNumber: 89, symbol: 'Ac', name: 'Actinium', atomicMass: 227, category: 'Actinide', group: null, period: 7, electronegativity: 1.1, meltingPoint: 1051, boilingPoint: 3198, density: 10.07, electronConfiguration: '[Rn] 6d¹ 7s²', description: 'Actinium is radioactive and used in cancer treatment research.'),
    ElementModel(atomicNumber: 90, symbol: 'Th', name: 'Thorium', atomicMass: 232.038, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 1750, boilingPoint: 4788, density: 11.72, electronConfiguration: '[Rn] 6d² 7s²', description: 'Thorium is a potential nuclear fuel that is more abundant than uranium.'),
    ElementModel(atomicNumber: 91, symbol: 'Pa', name: 'Protactinium', atomicMass: 231.036, category: 'Actinide', group: null, period: 7, electronegativity: 1.5, meltingPoint: 1572, boilingPoint: 4000, density: 15.37, electronConfiguration: '[Rn] 5f² 6d¹ 7s²', description: 'Protactinium is extremely rare and radioactive with no practical applications.'),
    ElementModel(atomicNumber: 93, symbol: 'Np', name: 'Neptunium', atomicMass: 237, category: 'Actinide', group: null, period: 7, electronegativity: 1.36, meltingPoint: 644, boilingPoint: 4000, density: 20.25, electronConfiguration: '[Rn] 5f⁴ 6d¹ 7s²', description: 'Neptunium is the first transuranium element and is used in neutron detection.'),
    ElementModel(atomicNumber: 94, symbol: 'Pu', name: 'Plutonium', atomicMass: 244, category: 'Actinide', group: null, period: 7, electronegativity: 1.28, meltingPoint: 640, boilingPoint: 3228, density: 19.86, electronConfiguration: '[Rn] 5f⁶ 7s²', description: 'Plutonium is used in nuclear weapons and reactors. It is extremely toxic.'),
    ElementModel(atomicNumber: 95, symbol: 'Am', name: 'Americium', atomicMass: 243, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 1176, boilingPoint: 2607, density: 13.69, electronConfiguration: '[Rn] 5f⁷ 7s²', description: 'Americium is used in smoke detectors and industrial gauges.'),
    ElementModel(atomicNumber: 96, symbol: 'Cm', name: 'Curium', atomicMass: 247, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 1345, boilingPoint: 3110, density: 13.51, electronConfiguration: '[Rn] 5f⁷ 6d¹ 7s²', description: 'Curium is named after Marie and Pierre Curie and is used in space missions.'),
    ElementModel(atomicNumber: 97, symbol: 'Bk', name: 'Berkelium', atomicMass: 247, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 1050, boilingPoint: 2627, density: 14.79, electronConfiguration: '[Rn] 5f⁹ 7s²', description: 'Berkelium is named after Berkeley, California, and has no practical applications.'),
    ElementModel(atomicNumber: 98, symbol: 'Cf', name: 'Californium', atomicMass: 251, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 900, boilingPoint: 1743, density: 15.1, electronConfiguration: '[Rn] 5f¹⁰ 7s²', description: 'Californium is used as a neutron source for starting nuclear reactors.'),
    ElementModel(atomicNumber: 99, symbol: 'Es', name: 'Einsteinium', atomicMass: 252, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 860, boilingPoint: 1130, density: 8.84, electronConfiguration: '[Rn] 5f¹¹ 7s²', description: 'Einsteinium is named after Albert Einstein and has no practical uses.'),
    ElementModel(atomicNumber: 100, symbol: 'Fm', name: 'Fermium', atomicMass: 257, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 1527, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹² 7s²', description: 'Fermium is named after Enrico Fermi and is used only in research.'),
    ElementModel(atomicNumber: 101, symbol: 'Md', name: 'Mendelevium', atomicMass: 258, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 827, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹³ 7s²', description: 'Mendelevium is named after Dmitri Mendeleev, creator of the periodic table.'),
    ElementModel(atomicNumber: 102, symbol: 'No', name: 'Nobelium', atomicMass: 259, category: 'Actinide', group: null, period: 7, electronegativity: 1.3, meltingPoint: 827, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 7s²', description: 'Nobelium is named after Alfred Nobel and has no known uses.'),
    ElementModel(atomicNumber: 103, symbol: 'Lr', name: 'Lawrencium', atomicMass: 262, category: 'Actinide', group: null, period: 7, electronegativity: null, meltingPoint: 1627, boilingPoint: null, density: null, electronConfiguration: '[Rn] 5f¹⁴ 7s² 7p¹', description: 'Lawrencium is named after Ernest Lawrence and is the last actinide element.'),
  ];
}
