import 'package:chem_earth_app/utils/import_export.dart';

final List<FormulaModel> formulaList = [
  FormulaModel(
    symbol: 'H₂O',
    name: 'Water',
    molWeight: '18.02',
    description: 'Colorless, odorless, tasteless liquid.',
    uses: 'Used in drinking, cleaning, and industrial processes.',
    bond: 'Polar covalent',
  ),
  FormulaModel(
    symbol: 'NaCl',
    name: 'Sodium Chloride',
    molWeight: '58.44',
    description: 'Ionic compound of sodium and chloride.',
    uses: 'Used as table salt and preservative.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'O₂',
    name: 'Oxygen',
    molWeight: '32.00',
    description: 'Diatomic gas essential for respiration.',
    uses: 'Breathing, combustion, steelmaking.',
    bond: 'Double covalent',
  ),
  FormulaModel(
    symbol: 'N₂',
    name: 'Nitrogen',
    molWeight: '28.02',
    description: 'Colorless, odorless diatomic gas.',
    uses: 'Cryogenics, inert atmosphere, ammonia production.',
    bond: 'Triple covalent',
  ),
  FormulaModel(
    symbol: 'HCl',
    name: 'Hydrochloric Acid',
    molWeight: '36.46',
    description: 'Strong, corrosive acid.',
    uses: 'Cleaning, digestion, chemical manufacturing.',
    bond: 'Polar covalent',
  ),
  FormulaModel(
    symbol: 'NaOH',
    name: 'Sodium Hydroxide',
    molWeight: '40.00',
    description: 'Caustic white solid.',
    uses: 'Soap making, drain cleaner, pH adjustment.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'KNO₃',
    name: 'Potassium Nitrate',
    molWeight: '101.10',
    description: 'White crystalline salt.',
    uses: 'Fertilizer, fireworks, gunpowder.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'HNO₃',
    name: 'Nitric Acid',
    molWeight: '63.01',
    description: 'Highly corrosive mineral acid.',
    uses: 'Fertilizer production, explosives, etching.',
    bond: 'Polar covalent',
  ),
  FormulaModel(
    symbol: 'CuSO₄',
    name: 'Copper(II) Sulfate',
    molWeight: '159.61',
    description: 'Blue crystalline solid.',
    uses: 'Fungicide, root killer, chemistry education.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'Ca(OH)₂',
    name: 'Calcium Hydroxide',
    molWeight: '74.09',
    description: 'White powder or colorless crystal.',
    uses: 'Construction (lime), water treatment.',
    bond: 'Ionic',
  ),
  FormulaModel(
    symbol: 'NaHCO₃',
    name: 'Sodium Bicarbonate (Baking Soda)',
    molWeight: '84.01',
    description: 'White crystalline powder.',
    uses: 'Baking, cleaning, antacid.',
    bond: 'Ionic',
  ),
];